import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const playFair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ['100','200','300','400','500','600','700','800','900'], 
  style: ['normal', 'italic'],
  display: 'swap',
  variable: '--font-poppins',
  preload: true,
  fallback: ['Arial', 'Helvetica', 'sans-serif'],
  adjustFontFallback: true,
  subsets: ['latin'],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playFair.variable} ${poppins.variable}  antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
